# Default values for peak.

replicaCount: 1

image:
  repository: docker.pkg.github.com/wealthbar/peak-design-system/peak-design-system
  tag: master
  pullPolicy: Always

service:
  name: peak
  type: NodePort
  port: 80
  targetPort: 5001

ingress:
  enabled: true

certificate:
  enabled: true

deployment:
  probePath: /

domains:
  - peak.wealth.bar

resources:
  limits:
    cpu: 20m
    memory: 110Mi
  requests:
    cpu: 10m
    memory: 80Mi

nodeSelector: {}

tolerations: []

affinity: {}
