kind: pipeline
name: test

steps:
  - name: test
    image: node:10-alpine
    environment:
      NODE_ENV: test
    commands:
      - yarn install
      - yarn run ci
    when:
      event: push

---
kind: pipeline
name: build-and-deploy-master

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: quay.io/wealthbar/peak-design-system
      registry: quay.io
      cache_from:
        - "quay.io/wealthbar/peak-design-system:master"
      tags:
        - latest
        - "${DRONE_COMMIT_SHA}"
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
    when:
      branch: master
      event: push

  - name: cluster-deploy
    image: cerebralchaos/do-k8s-helper:latest
    environment:
      CLUSTER_NAME:
        from_secret: cluster_name
      DIGITALOCEAN_ACCESS_TOKEN:
        from_secret: digitalocean_access_token
      CHART_REPO_USER:
        from_secret: chart_repo_user
      CHART_REPO_TOKEN:
        from_secret: chart_repo_token
    commands:
      - "doctl kubernetes cluster kubeconfig save $CLUSTER_NAME --access-token $DIGITALOCEAN_ACCESS_TOKEN"
      - "helm repo add --username $CHART_REPO_USER --password $CHART_REPO_TOKEN chartroom 'https://raw.githubusercontent.com/WealthBar/chartroom/master/'"
      - "helm repo update"
      - "helm upgrade --install peak chartroom/peak --namespace peak-design --set image.tag=${DRONE_COMMIT_SHA}"
    when:
      branch: master
      event: push

depends_on:
  - test
