image: "node:10-alpine"

variables:
  NODE_ENV: test
  CONTAINER_REGISTRY: quay.io/wealthbar
  CONTAINER_IMAGE: quay.io/wealthbar/$CI_PROJECT_NAME
  CONTAINER_TAG: quay.io/wealthbar/$CI_PROJECT_NAME:$CI_COMMIT_SHA
  KUBECONFIG: /etc/deploy/config
  CACHE_VERSION: 1

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
  script:
  - npm install node-sass
  - yarn install
  - yarn run ci
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  tags:
    - node
  cache:
    key: peak-$CACHE_VERSION
    paths:
      - node_modules

build_image:
  tags: [docker]
  stage: build   # build image only after test passed
  only: [master] # build and push images only for master branch commits
  image: docker:git # use simple git docker image
  services:
    - docker:dind
  script:
    - docker login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY
    - docker pull $CONTAINER_IMAGE:master
    - docker build --cache-from $CONTAINER_IMAGE:master -t $CONTAINER_TAG .
    - docker push $CONTAINER_TAG

deploy:
  stage: deploy
  only: [master]
  image: roffe/kubectl:v1.11.2
  environment:
    name: production
    url: https://peak.wealth.bar
  script:
    - mkdir -p /etc/deploy/
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl set image deployments/peak-deployment peak=quay.io/wealthbar/$CI_PROJECT_PATH:$CI_COMMIT_SHA
