image: "node:10-alpine"

# Cache gems and javascript modules in between builds
cache:
  untracked: true
  key: "packages-2018-05-23"
  paths:
  - node_modules/

variables:
  NODE_ENV: test
  CONTAINER_REGISTRY: gitlab.wealth.bar:4567
  CONTAINER_IMAGE: gitlab.wealth.bar:4567/$CI_PROJECT_PATH
  CONTAINER_TAG: gitlab.wealth.bar:4567/$CI_PROJECT_PATH:$CI_COMMIT_SHA
  KUBECONFIG: /etc/deploy/config
  CACHE_VERSION: 1

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
  script:
  - npm install node-sass
  - yarn install
  - yarn run ci
  artifacts:
    paths:
      - coverage/
    expire_in: 1 week
  tags:
    - node
  cache:
    key: peak-$CACHE_VERSION
    paths:
      - node_modules

build_image:
  tags: [docker]
  stage: build   # build image only after test passed
  only: [master] # build and push images only for master branch commits
  image: docker:git # use simple git docker image
  services:
    - docker:dind
  script:
    - docker login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY
    - docker pull $CONTAINER_IMAGE:latest
    - docker build --cache-from $CONTAINER_IMAGE:latest -t $CONTAINER_TAG -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_TAG
    - docker push $CONTAINER_IMAGE:latest

deploy:
  stage: deploy
  only: [master]
  image: roffe/kubectl:v1.11.2
  environment:
    name: production
    url: https://peak.wealth.bar
  script:
    - mkdir -p /etc/deploy/
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
    - kubectl set image deployments/peak-deployment peak=gitlab.wealth.bar:4567/$CI_PROJECT_PATH:$CI_COMMIT_SHA
