apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peak.fullname" . }}-deployment
  namespace: {{ .Release.Namespace}}
  labels:
    {{- include "peak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "peak.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "peak.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: wealthbar-ci-pull-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probePath }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probePath }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 30
            failureThreshold: 5