{{- if .Values.ingress.enabled -}}
{{- $service_port := .Values.service.port  -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "peak.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peak.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{ range .Values.domains }}
    {{- $service_name := . | replace "." "-" | trunc 63 | nospace -}}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $service_name }}
              servicePort: {{ $service_port }}
    {{ end -}}
  {{- if .Values.certificate.enabled }}
  tls:
    {{- range .Values.domains }}
    {{- $service_name := . | replace "." "-" | trunc 63 | nospace }}
    - secretName: {{ $service_name }}-prod-tls
      hosts:
        - {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
