apiVersion: v1
kind: Service
metadata:
  name: {{ include "peak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "peak.name" . }}
    release: {{ .Release.Name }}
    {{- include "peak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
  selector:
    app: {{ include "peak.name" . }}
    release: {{ .Release.Name }}
    {{- include "peak.selectorLabels" . | nindent 4 }}
