apiVersion: v1
kind: Service
metadata:
  name: {{ include "peak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.targetPort }}
  selector:
    {{- include "peak.selectorLabels" . | nindent 4 }}
