name: Build and deploy to production
on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10

    - name: Run tests
      run: |
        yarn install
        yarn run ci

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      env:
        CONTAINER_IMAGE: quay.io/wealthbar/peak-design-system
        CONTAINER_REGISTRY: quay.io/wealthbar
        REGISTRY_USER: ${{ secrets.registry_user }}
        REGISTRY_KEY: ${{ secrets.registry_key }}
      run: |
        docker login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY
        docker pull $CONTAINER_IMAGE:latest || true
        docker build --cache-from $CONTAINER_IMAGE:latest --build-arg CI_COMMIT_SHA=$GITHUB_SHA -t $CONTAINER_IMAGE:$GITHUB_SHA -t $CONTAINER_IMAGE:latest .
      
    needs: test
