name: Build and deploy to production
on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: actions/checkout@v1

    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10.x

    - name: Run tests
      run: |
        yarn install
        yarn run ci

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Build
      env:
        CONTAINER_IMAGE: quay.io/wealthbar/peak-design-system
        CONTAINER_REGISTRY: quay.io/wealthbar
        REGISTRY_USER: ${{ secrets.registry_user }}
        REGISTRY_KEY: ${{ secrets.registry_key }}
      run: |
        docker login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY
        docker pull $CONTAINER_IMAGE:latest || true
        docker build --cache-from $CONTAINER_IMAGE:latest --build-arg CI_COMMIT_SHA=$GITHUB_SHA -t $CONTAINER_IMAGE:$GITHUB_SHA -t $CONTAINER_IMAGE:latest .
    
  push_to_quay:
    runs-on: ubuntu-latest
    steps:
    - name: Push to Quay
      env:
        CONTAINER_IMAGE: quay.io/wealthbar/peak-design-system
        CONTAINER_REGISTRY: quay.io/wealthbar
        REGISTRY_USER: ${{ secrets.registry_user }}
        REGISTRY_KEY: ${{ secrets.registry_key }}
      run: |
        docker login $CONTAINER_REGISTRY -u $REGISTRY_USER -p $REGISTRY_KEY
        docker push $CONTAINER_IMAGE:$GITHUB_SHA
        docker push $CONTAINER_IMAGE:latest
      
    needs: [test, build]
    
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        CLUSTER_NAME: ${{ secrets.cluster_name }}
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.digitalocean_access_token }}
      with:
        args: '"kubernetes cluster kubeconfig show $CLUSTER_NAME > $HOME/.kubeconfig"'
        
    - name: Deploy to Kubernetes cluster
      uses: docker://lachlanevenson/k8s-kubectl
      with:
        entrypoint: sh
        args: -l -c "kubectl --kubeconfig=$HOME/.kubeconfig set image deployments/peak-deployment peak=quay.io/wealthbar/peak-design-system:${GITHUB_SHA}"
        
    - name: Verify deployment
      uses: docker://lachlanevenson/k8s-kubectl
      env:
        DEPLOYMENT: peak-deployment
      with:
        entrypoint: sh
        args: -l -c "kubectl --kubeconfig=$HOME/.kubeconfig rollout status deployment/$DEPLOYMENT"
    
    needs: push_to_quay
