name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: actions/checkout@v1

      - name: Use Node.js 11
        uses: actions/setup-node@v1
        with:
          version: 11.10.x

      - name: Run tests
        run: |
          yarn install
          yarn run ci
